[package]
name = "grayline-sstv-template"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
image.workspace = true
jiff.workspace = true
kdl.workspace = true
resvg.workspace = true
grayline-sstv = { path = "../sstv" }
grayline-variables = { path = "../variables" }
thiserror = { workspace = true, features = ["std"] }

[dev-dependencies]
proptest.workspace = true
rstest.workspace = true
