[package]
name = "grayline-decode-wav"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "decode-wav"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
hound.workspace = true
image.workspace = true
grayline-sstv-rx = { path = "../../crates/sstv-rx" }
grayline-sstv-fskid = { path = "../../crates/sstv-fskid" }
grayline-sstv = { path = "../../crates/sstv", features = ["std"] }
