[package]
name = "grayline-wefax"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
bench = false

[features]
default = []
std = ["thiserror/std", "grayline-dsp/std"]

[dependencies]
grayline-dsp = { path = "../dsp" }
libm.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
rstest.workspace = true

[[bench]]
name = "receive"
harness = false
