[package]
name = "grayline-dsp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
bench = false

[features]
default = []
std = ["thiserror/std"]

[dependencies]
libm.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
rstest.workspace = true

[[bench]]
name = "primitives"
harness = false
