[package]
name = "grayline-wefax-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "gl-wefax"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
hound.workspace = true
image.workspace = true
grayline-wefax = { path = "../../crates/wefax", features = ["std"] }
